# Generated by Django 5.1.4 on 2025-06-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropimage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ne', 'Nepali'), ('hi', 'Hindi')], default='en', help_text='Language used for AI analysis and result display.', max_length=10, verbose_name='Language'),
        ),
    ]
